common/urls.py
from common import views
from django.urls import path

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),
]

fruitpedia/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('fruit', include('fruits.urls')),
    path('profile/', include('profiles.urls')),
]

fruits/urls.py
from django.urls import path
from django.urls.conf import include

from fruits import views

urlpatterns = [
    path('create/', views.CreateFruit.as_view(), name='fruit-create'),
    path('<int:id>/', include([
        path('details/', views.details_fruit, name='fruit-details'),
        path('edit/', views.EditFruit.as_view(), name='fruit-edit'),
        path('delete/', views.delete_fruit, name='fruit-delete'),
    ]))
]

profiles/urls.py
from django.urls import path

from profiles import views

urlpatterns = [
    path('create/', views.CreateProfile.as_view(), name='profile-create'),
    path('details', views.details_profile, name='profile-details'),
    path('edit', views.EditProfile.as_view(), name='profile-edit'),
    path('delete/', views.delete_profile, name='profile-delete'),
]

common/models.py
from django.db import models

# Create your models here.

fruits/models.py
from django.core.validators import MinLengthValidator
from django.db import models
from fruits.validators import fruit_name_validator
from profiles.models import Profile


class Fruit(models.Model):
    name = models.CharField(
        max_length=30,
        unique=True,
        validators=[
            MinLengthValidator(2),
            fruit_name_validator,
        ],
        error_messages={
            'unique': 'This fruit name is already in use! Try a new one.'
        }
    )

    image = models.URLField()

    description = models.TextField()

    nutrition = models.TextField(blank=True, null=True)

    owner = models.ForeignKey(Profile, on_delete=models.CASCADE)

profiles/models.py
from django.core.validators import MinLengthValidator
from django.db import models
from profiles.validators import first_letter_validator


class Profile(models.Model):
    first_name = models.CharField(
        max_length=25,
        validators=[
            MinLengthValidator(2),
            first_letter_validator,
        ]
    )

    last_name = models.CharField(
        max_length=35,
        validators=[
            MinLengthValidator(1),
            first_letter_validator,
        ]
    )

    email = models.EmailField(max_length=40)

    password = models.CharField(
        help_text='*Password length requirements: 8 to 20 characters',
        max_length=20,
        validators=[
            MinLengthValidator(8),
        ]
    )

    image = models.URLField(blank=True, null=True)

    age = models.IntegerField(null=True, blank=True, default=18)

fruits/forms.py
from fruits.models import Fruit
from django import forms


class CreateFruitForm(forms.ModelForm):
    class Meta:
        model = Fruit
        exclude = ['owner']

        labels = {
            'name': '',
            'image': '',
            'description': '',
            'nutrition': ''
        }

        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Fruit Name'}),
            'image': forms.TextInput(attrs={'placeholder': 'Fruit image URL'}),
            'description': forms.Textarea(attrs={'placeholder': 'Fruit Description'}),
            'nutrition': forms.Textarea(attrs={'placeholder': 'Nutrition Info'}),
        }



class DeleteFruitForm(CreateFruitForm):
    def __init__(self, *args, **kwargs):
        super(DeleteFruitForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['readonly'] = True

profiles/forms.py
from django import forms

from profiles.models import Profile


class CreateProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['image', 'age']

        labels = {
            'first_name': '',
            'last_name': '',
            'email': '',
            'password': ''
        }

        widgets = {
            'first_name': forms.TextInput(attrs={'placeholder': 'First Name'}),
            'last_name': forms.TextInput(attrs={'placeholder': 'Last Name'}),
            'email': forms.TextInput(attrs={'placeholder': 'Email'}),
            'password': forms.PasswordInput(attrs={'placeholder': 'Password'}),

        }


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['email', 'password']

common/views.py
from django.shortcuts import render
from django.views.generic import ListView

from fruits.models import Fruit
from profiles.models import Profile


# Create your views here.


def index(request):
    profile = Profile.objects.first()
    context = {
        'profile': profile
    }

    return render(request, 'common/index.html', context)


class Dashboard(ListView):
    template_name = 'common/dashboard.html'
    model = Fruit

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profile'] = Profile.objects.first()
        return context

fruits/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, UpdateView, DeleteView

from fruits.forms import CreateFruitForm, DeleteFruitForm
from fruits.models import Fruit
from django.urls import reverse_lazy

from profiles.models import Profile


class CreateFruit(CreateView):
    model = Fruit
    form_class = CreateFruitForm
    template_name = 'fruits/create-fruit.html'
    success_url = reverse_lazy('dashboard')

    def form_valid(self, form):
        form.instance.owner = Profile.objects.first()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profile'] = Profile.objects.first()
        return context


class EditFruit(UpdateView):
    model = Fruit
    form_class = CreateFruitForm
    pk_url_kwarg = 'id'
    template_name = 'fruits/edit-fruit.html'
    success_url = reverse_lazy('dashboard')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profile'] = Profile.objects.first()
        return context


def delete_fruit(request, id):
    fruit = Fruit.objects.get(pk=id)
    profile = Profile.objects.first()
    form = DeleteFruitForm(instance=fruit)

    context = {
        'fruit': fruit,
        'profile': profile,
        'form': form
    }

    if request.method == 'POST':
        fruit.delete()
        return redirect('dashboard')

    return render(request, 'fruits/delete-fruit.html', context)


def details_fruit(request, id):
    fruit = Fruit.objects.get(pk=id)
    profile = Profile.objects.first()

    context = {
        'fruit': fruit,
        'profile': profile,
    }

    return render(request, 'fruits/details-fruit.html', context)

profiles/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, UpdateView

from profiles.forms import CreateProfileForm, EditProfileForm
from profiles.models import Profile
from django.urls import reverse_lazy


class CreateProfile(CreateView):
    model = Profile
    form_class = CreateProfileForm
    template_name = 'profiles/create-profile.html'
    success_url = reverse_lazy('dashboard')


def details_profile(request):
    profile = Profile.objects.first()
    posts = profile.fruit_set.all().count()

    context = {
        'profile': profile,
        'posts': posts,
    }

    return render(request, 'profiles/details-profile.html', context)


class EditProfile(UpdateView):
    model = Profile
    form_class = EditProfileForm
    template_name = 'profiles/edit-profile.html'
    success_url = reverse_lazy('dashboard')

    def get_object(self,queryset=None):
        return Profile.objects.first()


def delete_profile(request):
    profile = Profile.objects.first()
    context = {
        'profile': profile,
    }

    if request.method == 'POST':
        profile.delete()
        return redirect('index')

    return render(request, 'profiles/delete-profile.html', context)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=\, initial-scale=1.0"/>
    <link rel="stylesheet" href="{% static 'styles/styles.css' %}"/>
    <title>Fruitipedia</title>
</head>
<body>
<div id="wrapper">
    <header>
        <!-- Navigation -->
        <a id="logo" href="{% url 'index' %}">
            <img id="logo-img" src="{% static 'images/logo.png' %}" alt="logo"/>
        </a>

        <nav>

            <!-- If there is a user profile -->
            {% if profile %}
            <div class="user">
                <a href="{% url 'dashboard' %}">Dashboard</a>
                <a href="{% url 'fruit-create' %}">Add Fruit</a>
                <a href="{% url 'profile-details' %}">Profile</a>
            </div>
            {% else %}
            <!-- If user profile has NOT been created -->
            <div class="guest">

                <a href="{% url 'profile-create' %}">Create Profile</a>

            </div>
            {% endif %}
        </nav>
    </header>

    {% block content %}
    {% endblock %}

<!-- footer -->
<footer>
    <p>@Fruitipedia - SoftUni Team 2023. All rights reserved.</p>
</footer>
</body>
</html>

templates/common/dashboard.html
|{% extends 'base.html' %}
{% block content %}

    <main>

        <!-- Dashboard Page -->
        
        {% if not fruit_list %}
        <h2>No fruit info yet.</h2>
        {% else %}

        <h2>Fruits</h2>
        <section id="dashboard">
            <!-- Display a div "fruit" with information about each post (if any)-->
             {% for fruit in fruit_list %}
            <!-- first fruit -->
            <div class="fruit">
                <!-- fruit image -->
                <img src="{{fruit.image }}" alt="example1"/>
                <!-- fruit name -->
                <h3 class="title">{{ fruit.name }}</h3>
                <!-- fruit description -->
                <p class="description">{{ fruit.description|slice:'50'}}</p>
                <!-- fruit details button -->
                <a class="details-btn" href="{% url 'fruit-details' fruit.pk %}">More Info</a>
            </div>
        {% endfor %}
        </section>

        {% endif %}

        <!-- Display a heading if there are no posts -->


    </main>
{% endblock %}

templates/common/index.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

    <main>
        <!-- Home page -->
        <section id="home">
          <h1>Learn more about your favorite fruits</h1>
          <img
            src="{% static 'images/pexels-pixabay-161559-dImkWBDHz-transformed%20(1).png' %}"
            alt="home"
          />

        </section>

      </main>

{% endblock %}

templates/fruits/create-fruit.html
{% extends 'base.html' %}
{% block content %}

    <main>
        <!-- Add Fruit Form -->
        <section id="create">
            <div class="form" >
                <h2>Add Fruit</h2>
                <form class="create-form" method="post">
                   {% csrf_token %}
                    {{ form }}
                    <button type="submit">Add Fruit</button>
                </form>
            </div>
        </section>
    </main>

<!-- footer -->
{% endblock %}

templates/fruits/delete-fruit.html
{% extends 'base.html' %}
{% block content %}

    <main>

        <!-- Delete Fruit Form -->
        <section id="edit">
            
                <div class="form">
                    <h2>Delete Fruit</h2>
                    <form class="edit-form" method="post">
                        {% csrf_token %}
                        {{ form }}
                        <button type="submit">Delete</button>
                    </form>
                </div>
           
        </section>

    </main>
{% endblock %}

templates/fruits/details-fruit.html
{% extends 'base.html' %}
{% block content %}

    <main>

        <!-- Fruit Details -->
        <section id="details">
            <div id="details-wrapper">
                <!-- fruit image -->
                <img id="details-img" src="{{ fruit.image }}" alt="example1"/>
                <!-- fruit name -->
                <p id="details-title">{{ fruit.name }}</p>
                <div id="info-wrapper">
                    <div id="details-description">
                        <!-- fruit description -->
                        <p>
                            {{ fruit.description }}
                        </p>
                        <!-- fruit nutrition -->
                        <p id="nutrition">Nutrition</p>
                        <!-- fruit nutrition details -->
                        <p id="details-nutrition">
                            {{ fruit.nutrition }}
                        </p>
                    </div>

                    <!--Edit and Delete buttons -->
                    <div id="action-buttons">
                        <a href="{% url 'fruit-edit' fruit.pk %}" id="edit-btn">Edit</a>
                        <a href="{% url 'fruit-delete' fruit.pk %}" id="delete-btn">Delete</a>
                    </div>
                </div>
            </div>
        </section>

    </main>
{% endblock %}

templates/fruits/edit-fruit.html
{% extends 'base.html' %}
{% block content %}

    <main>

        <!-- Edit Fruit Form -->
        <section id="edit">
            <div class="form">
                <h2>Edit Fruit</h2>
                <form class="edit-form" method="post">
                    {% csrf_token %}
                    {{ form }}
                    <button type="submit">Edit</button>
                </form>
            </div>
        </section>

    </main>
{% endblock %}

templates/profiles/create-profile.html
{% extends 'base.html' %}
{% block content %}


      <main>
        <!-- Create Profile Form -->
        <section id="register">
          <div class="form">
            <h2>Create Profile</h2>
            <form method='post' class="register-form">
                {% csrf_token %}
                {{ form }}

              <button type="submit">Create</button>
            </form>
          </div>
        </section>
      </main>
{% endblock %}

templates/profiles/delete-profile.html
{% extends 'base.html' %}
{% block content %}


    <main>

        <section id="edit">

            <div class="form">
                <h1>Are you sure you want to delete your profile?</h1>
                
                <!-- Delete Profile Form -->
                <form method="post" id='delete' class="register-form">
                    {% csrf_token %}
                    <button type="submit">Yes</button>

                </form>
                <!-- End Delete Profile Form -->
            </div>
            
        </section>
    </main>
{% endblock %}

templates/profiles/details-profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


    <main>

        <!-- Profile Details Section -->

        <section id="details">
            <div id="details-wrapper">
                <h2>Profile Details</h2>
                {% if profile.image %}
                <img id="details-img" src="{{ profile.image }}"
                     alt="profile img"/>

                {% else %}
                <img id="details-img" src="{% static 'images/default.jpg' %}" alt="profile img"/>
                {% endif %}
                <!-- user's full name -->
                <p id="details-title">{{ profile.first_name}} {{ profile.last_name }}</p>

                <div id="info-wrapper">
                    <div id="details-description">
                        <!-- email -->
                        <p>
                            {{ profile.email }}
                        </p>
                        <!-- age -->
                        <p>
                            Age: {{ profile.age }}
                        </p>
                        <!-- number of posts -->
                        <p id="nutrition">Posts: {% if posts %}{{ posts }}{% else %}0{% endif %}</p>

                    </div>

                    <!--Edit and Delete buttons -->
                    <div id="action-buttons">
                        <a href="{% url 'profile-edit' %}" id="edit-btn">Edit</a>
                        <a href="{% url 'profile-delete' %}" id="delete-btn">Delete</a>
                    </div>
                </div>
            </div>
        </section>

    </main>
{% endblock %}

templates/profiles/edit-profile.html
{% extends 'base.html' %}
{% block content %}

    <main>

        <!-- Edit Profile Form -->

        <section id="register">
            <div class="form">
                <h2>Edit Profile</h2>
                <form class="register-form" method="post">
                    {% csrf_token %}
                    {{ form }}
                    <button type="submit">Edit</button>

                </form>
            </div>
        </section>

    </main>
{% endblock %}